[build]
target = "C:\\Users\\mc\\Desktop\\rust\\blog_os\\x86_64-blog_os.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
